-- MySQL Script generated by MySQL Workbench
-- Wed May 26 11:41:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compras` (
  `Codigo do produto` CHAR(6) NOT NULL,
  `Valor de aquisição` FLOAT NOT NULL,
  `Descrição` TINYTEXT NOT NULL,
  `Data de validade` DATE NOT NULL,
  `Categoria` VARCHAR(20) NOT NULL,
  `Quantidade` INT NOT NULL,
  `Data de aquisição` DATE NOT NULL,
  `Fornecedor` VARCHAR(20) NOT NULL,
  `Estoque_Codigo do produto` CHAR(6) NOT NULL,
  `Estoque_Usuário_Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo do produto`, `Estoque_Codigo do produto`, `Estoque_Usuário_Email`),
  INDEX `fk_Compras_Estoque1_idx` (`Estoque_Codigo do produto` ASC, `Estoque_Usuário_Email` ASC) VISIBLE,
  CONSTRAINT `fk_Compras_Estoque1`
    FOREIGN KEY (`Estoque_Codigo do produto` , `Estoque_Usuário_Email`)
    REFERENCES `mydb`.`Estoque` (`Codigo do produto` , `Usuário_Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `Codigo do produto` CHAR(6) NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Descrição` TINYTEXT NOT NULL,
  `Data de validade` DATE NOT NULL,
  `Posição` INT NOT NULL,
  `Armazém` INT NOT NULL,
  `Categoria` VARCHAR(20) NOT NULL,
  `Prateleira` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Usuário_Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo do produto`, `Usuário_Email`),
  INDEX `fk_Estoque_Usuário_idx` (`Usuário_Email` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Usuário`
    FOREIGN KEY (`Usuário_Email`)
    REFERENCES `mydb`.`Usuário` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuário` (
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(32) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Empresa` VARCHAR(45) NOT NULL,
  `Usuário` VARCHAR(45) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `CNPJ` CHAR(14) NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
